/* Phrases split out so the jargon list can be edited independently of page logic. */
window.CORPORATE_PHRASES = [
  "Bandwidth",
  "Bang For Your Buck",
  "Blue Sky Thinking",
  "Buy-In",
  "Cadence",
  "Circle Back",
  "Deep Dive",
  "Disruptive",
  "Get Ducks In A Row",
  "Hit The Ground Running",
  "Hard Stop",
  "Jump Start",
  "Lean In",
  "Let's Circle Back",
  "Let's Take This Offline",
  "Leverage",
  "Low Hanging Fruit",
  "Move The Needle",
  "Moving Parts",
  "No Brainer",
  "Offload",
  "On The Radar",
  "Optics",
  "Pain Points",
  "Pivot",
  "Put On The Record",
  "Reinvent The Wheel",
  "Singing From The Same Hymn Sheet",
  "Special Sauce",
  "Streamline",
  "Synergy",
  "The Bottom Line",
  "There Seems To Be A Disconnect",
  "Thinking Outside The Box",
  "Under The Bonnet",
  "Unpack",
  "Up The Ladder",
  "Wheelhouse",
  "Win-Win",
  "Ideate",
  "Right-Sizing",
  "Future-Proof",
  "Mission Critical",
  "Circle Of Excellence",
  "Touch Base",
  "Value Add",
  "Granular",
  "Tiger Team",
  "North Star",
  "Action Items",
  "All Hands On Deck",
  "Boil The Ocean",
  "Business Critical",
  "Change Agent",
  "Closing The Loop",
  "Core Competency",
  "Critical Path",
  "Customer Obsession",
  "Data-Driven",
  "Deliverables",
  "Digital Transformation",
  "Drill Down",
  "Fail Fast",
  "Game Changer",
  "Going Forward",
  "Greenfield Opportunity",
  "Holistic Approach",
  "Hypergrowth",
  "Key Takeaway",
  "KPI",
  "Land And Expand",
  "Lessons Learned",
  "Line Of Sight",
  "Mission Alignment",
  "Net Net",
  "Open The Kimono",
  "Operationalize",
  "Paradigm Shift",
  "Parking Lot That",
  "Proactive Outreach",
  "Quick Win",
  "Reach Out",
  "Right The Ship",
  "Robust Solution",
  "Run It Up The Flagpole",
  "Scalable",
  "Single Source Of Truth",
  "Stakeholder Buy-In",
  "Swim Lane",
  "Take It Offline",
  "Thought Leader",
  "Touchpoints",
  "Value Proposition",
  "Vet This",
  "Voice Of The Customer",
  "Wheel And Deal",
  "Zero Sum Game"
];
